# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 정우섭 | 끊임없이 배우고싶은 개발자
title: Junior Machine Learning Engineer
# email: wjddntjq15@naver.com
# website: https://tjqdnwj.tistory.com/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: JWseop
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: J's Study Log
  icon: fas fa-globe
  url: https://tjqdnwj.tistory.com/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs  # <mark>강조단어</mark>
  생년월일: 1999.01.26


  전화번호: 010-9434-1499


  email: wjddntjq15@naver.com


  GitHub: [https://github.com/JWseop](https://github.com/JWseop)


  Blog: [https://tjqdnwj.tistory.com/](https://tjqdnwj.tistory.com/)

content:
  - title: Introduce # Title for the section
    layout: list # Type of content section (list/text)
    content:
    ### 프로젝트 1   # <mark>강조단어</mark>
      - layout: top-middle
        description: | 
          과감한 도전을 했습니다.


          새로운 혁신을 실현시키기 위하여 AI기술학 및 경영학 복수전공이 중요하다 생각했습니다. 실제로 복수전공으로 변경시 졸업이 불확실해지는 상황에도 불구하고 과감하게 도전하였습니다. 1전공자에게 밀려 수강이 불가했던 강의들을 방학때 전부 수강하여 그 학점이 한학기에 듣는 정도에 달했습니다. 그 결과, 불가능해 보였던 복수전공 학위를 4학년 2학기 졸업에 맞춰 획득할 수 있었습니다.
          전력투구하며 쌓아온 기술적인 능력과 경영지식을 AI 서비스 개발 및 기술지원 엔지니어 포지션에서 새로운 가치를 만들어가는데 기여하겠습니다.


          역지사지로 협력합니다.

          
          클라우드 컴퓨팅 프로젝트 당시 빠듯한 스케줄 속 돌방상황을 역지사지 커뮤니케이션으로 팀원들과 함께 극복하였습니다.
          3달간의 프로젝트에서 마감 2주를 남기고 팀원 한명이 갑작스럽게 그만두어 업무배분과 스케줄운영에 어려움을 겪었습니다. 모든 팀원들이 기말고사 일정을 소화해야하기 때문에 곤란하였지만, 남은 4명의 팀원끼리 서로의 상황을 이해하고 각자의 능력과 투입가능한 스케줄을 조율하여 신속하게 대응해 나갔습니다. 팀원들과 함께 소통하고 조율하여 프로젝트는 최고점으로 마무리하였습니다.
          이러한 경험을 바탕으로 Tmax에서 팀원들과 다른 부서 사람들과 역지사지로 협력하며 효율적으로 기여하겠습니다.



        # 혁신에 올인 하고싶은 개발자 정우섭 입니다. 새로운 가치를 실현시키기 위해 끊임없이 도전해왔습니다.
          
          
        # 그래서 혁신의 아이콘으로 떠오르는 인공지능 관련 강의를 전부 이수했습니다. 특히, 머신러닝의 지도학습 및 강화학습 관련 강의를 다수 수강 했습니다.
          

          # 누군가의 고민을 해결해줄 수 있는 프로그램을 만들기 위해서는 <mark>비즈니스적 시야</mark>가 필수적이라 생각했습니다. 그래서 저는 경영학을 배우기로 마음을 먹고 <mark>경영학을 복수전공</mark> 했습니다.
          

          # 그 결과, 이번 TABA3기 프로젝트에서 고령자의 고민을 해결해주기 위한 '약 사전' 앱을 개발했습니다. 개발을 효율적으로 수행하기 위해서 팀원들과의 소통이 얼마나 중요한지 인지하고 있기에 <mark>팀원들과의 적극적인 커뮤니케이션</mark>을 하며 업무를 수행한 결과 <mark>우수상</mark>을 수상 할 수 있었습니다.
          

          # 혁신을 위해 전력투구하며 쌓아온 지식과 경험을 TmaxAI에서 'AI 서비스 개발 및 기술지원 엔지니어'로서 새로운 도전과 가치실현에 기여하고 싶습니다.
          
          
        # Junior Machine Learning Engineer 정우섭 입니다. 저는 인공지능 관련 강의를 위주로 학점을 이수했습니다. 특히, 머신러닝의 지도학습 및 강화학습 관련 강의를 다수 수강했습니다. 그 후, 여러 공모전 및 프로젝트를 통해 강의에서 배운 이론을 활용한 프로젝트 수행 능력을 길렀습니다.


        # 항상 목표지향적으로 움직여 목표를 정하고, 이를 달성하기 위해 무슨 일을 해야 하는지 계획하고 움직입니다. 경영학과를 복수전공하며 배운 지식을 통해 더 좋은 목표를 세우는 전략과 추진력을 갖추게 해주었습니다.


        # 업무를 항상 효율적으로 수행하는 것을 좋아합니다. 이를 위해, 팀원들과의 소통이 얼마나 중요한지 인지하고 있기 때문에 팀원들과의 적극적인 커뮤니케이션을 하기 위해 노력합니다.

  - title: Projects # Title for the section 
    layout: list # Type of content section (list/text)
    content:
    ### 프로젝트 1
      - layout: top-left
        title: 캡스톤 프로젝트
        # link: github.com/Manner-Maketh-Man/Presentation
        # link_text: Git Repository Link
        additional_links:
          - title:  github.com/Manner-Maketh-Man/Presentation
            icon: fab fa-github
            url: github.com/Manner-Maketh-Man/Presentation
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        sub_title: Project Manager
        description: | # this will include new lines to allow paragraphs
          실시간으로 채팅에 대한 감정분석을 진행해, 상대방의 현재 감정을 이모티콘으로 보여주는 프로그램
          - 전체 아키텍쳐 디자인

          - fine-tuning 모델 앙상블 구현 (KoGPT, KoBERT, KoELECTRA)

          - 클로바 OCR API 연동

          - PyQt5를 활용한 GUI 구현

          - Presentation

      ### 프로젝트 2
      - layout: top-left
        title: TABA 팀 프로젝트:약 사전
        # link: https://github.com/Receipt-Information-Parser/Service
        # link_text: Git Repository Link
        # additional_links:
        #   - title:  Receipt Information Parser
        #     icon: fab fa-github
        #     url: https://github.com/Receipt-Information-Parser/Service
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        sub_title: Project Manager 
        description: | # this will include new lines to allow paragraphs
          Computer Vision 기술을 알약사진에 사용한 알약 검색 앱 
          - Triton Inference Server 구현

          - ResNet152 모델 학습

          - 데이터 전처리

          - Flutter를 활용한 앱 UI/UX 구현

      ### 프로젝트 3
      - layout: top-left
        title: 클라우드 컴퓨팅 프로젝트
        # link: https://github.com/Receipt-Information-Parser/Service
        # link_text: Git Repository Link
        additional_links:
          - title:  Receipt Information Parser
            icon: fab fa-github
            url: https://github.com/Receipt-Information-Parser/Service
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        sub_title: Inference Server Engineer & Frontend Engineer
        description: | # this will include new lines to allow paragraphs
          OCR 기술을 활용한 영수증 촬영을 통한 자동 가계부 작성 앱
          - 영수증 OCR 결과에 대한 NER 구현

          - Flutter를 활용한 앱 UI/UX 구현
      
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Deep Learning Study Group
        link: https://github.com/floodsung/Deep-Learning-Papers-Reading-Roadmap
        link_text: Roadmap link
        caption: 2023.01 - 2023.03
        sub_title: DKUCILAB - 2022 Winter Deep Learning Study Group
        description: | 
          단국대학교 모바일시스템공학과 이규행 교수님과 주 1회 진행한 논문리뷰 세미나 입니다. 세계적 석학인 floodsung의 Deep Learning Papers Reading Roadmap을 따라 진행하였습니다.


          가장 흥미로웠던 논문은 'Ask me Anything: Dynamic Memory Networks for Natural Language Processing'입니다. Memory Network가 작동하는 메커니즘도 신기했지만, attention 개념을 처음 접하면서 많은 공부가 됐던 기억이 있습니다.

      - layout: left
        title: 스타트업 하계인턴십
        # link: boringcompany.com
        # link_text: boringcompany.com
        caption: 2022.06 - 2022.07
        sub_title: 단국대학교 창업지원단
        description: | 
          - 고객 데이터 분석
          
          - R을 사용한 데이터의 시각화 및 데이터 분석의 자동화

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 단국대학교 졸업(예정)
        caption: 2018.03 - 2024.02
        sub_title: 모바일시스템공학과 & 경영학과
        description: | 
          저는 모바일시스템공학과를 통해 학습한 개발 지식과 경영학의 전략적 사고방식을 통합하여, 기술을 사업의 성공으로 이끌 수 있는 능력을 키워왔습니다. 엔지니어로 입사해 기술적 역량을 키운 후, 미래에는 실력있는 PM이 되어 기술과 비즈니스 사이의 가교 역할을 하며, 회사의 성공을 위해 기여하는 인재로 성장하고 싶습니다.

      - layout: left
        title: 캠퍼스SW아카데미 TABA 3기 수료
        caption: 2023.06 - 2023.08
        sub_title: 프로젝트 우수상 & 우수학생상
        description: | 
          TmaxTibero, 단국대학교, 한국클라우드컴퓨팅연구조합과 함께하는 프로젝트에서 우수한 성과를 거두었고, 이론 및 실습 역량을 증명받아 IITP 원장상도 수상하였습니다.
      
      - layout: left
        title: 고급SW코딩캠프
        caption: 2021.08
        sub_title: 딥러닝입문
        description: | 
          단국대학교SW중심대학사업단에서 주관한 교육 프로그램 입니다. 해당 교육을 통해 2학년부터 딥러닝을 배우고 관심을 갖게 되었습니다. 이는 제가 인공지능 커리큘럼을 교육받고 졸업하게된 계기가 되었습니다.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      - 단국대-다우기술 대학생 프로그래밍 경진대회 2022, 은상(2등)
      - 2022 용인시-단국대 SW상생혁샌캠퍼스데이, 우수상
      - 성적장학금 6회

    ### Look at this cool image  
      # ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
